/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExpense: typeof import('./src/components/Finances/Expenses/AddExpense.vue')['default']
    AddTransaction: typeof import('./src/components/Finances/AddTransaction.vue')['default']
    AgendaBacklog: typeof import('./src/components/AgendaOld/AgendaBacklog.vue')['default']
    AgendaContainer: typeof import('./src/components/Agenda/AgendaContainer.vue')['default']
    AgendaDay: typeof import('./src/components/AgendaOld/AgendaDay.vue')['default']
    AgendaGrid: typeof import('./src/components/AgendaOld/AgendaGrid.vue')['default']
    AgendaTask: typeof import('./src/components/AgendaOld/AgendaTask.vue')['default']
    AgendaTimeslot: typeof import('./src/components/AgendaOld/AgendaTimeslot.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CategoryMeterGroup: typeof import('./src/components/Finances/CategoryMeterGroup.vue')['default']
    CategoryMeterGroups: typeof import('./src/components/Finances/CategoryMeterGroups.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditExpense: typeof import('./src/components/Finances/Expenses/EditExpense.vue')['default']
    EditTask: typeof import('./src/components/Agenda/EditTask.vue')['default']
    EditTransaction: typeof import('./src/components/Finances/EditTransaction.vue')['default']
    ExpensesList: typeof import('./src/components/Finances/Expenses/ExpensesList.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Task: typeof import('./src/components/Agenda/Task.vue')['default']
    Tasks: typeof import('./src/components/Dashboard/Tasks.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TransactionHistory: typeof import('./src/components/Finances/TransactionHistory.vue')['default']
    Weather: typeof import('./src/components/Dashboard/Weather/Weather.vue')['default']
    WeatherHour: typeof import('./src/components/Dashboard/Weather/WeatherHour.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
