/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExpense: typeof import('./src/components/Finances/Expenses/AddExpense.vue')['default']
    AddTransaction: typeof import('./src/components/Finances/AddTransaction.vue')['default']
    AddWorkout: typeof import('./src/components/Fitness/AddWorkout.vue')['default']
    AgendaBacklog: typeof import('./src/components/AgendaOld/AgendaBacklog.vue')['default']
    AgendaContainer: typeof import('./src/components/Agenda/AgendaContainer.vue')['default']
    AgendaDay: typeof import('./src/components/AgendaOld/AgendaDay.vue')['default']
    AgendaGrid: typeof import('./src/components/AgendaOld/AgendaGrid.vue')['default']
    AgendaTask: typeof import('./src/components/AgendaOld/AgendaTask.vue')['default']
    AgendaTimeslot: typeof import('./src/components/AgendaOld/AgendaTimeslot.vue')['default']
    BudgetList: typeof import('./src/components/Finances/BudgetList.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CategoryMeterGroups: typeof import('./src/components/Finances/CategoryMeterGroups.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DashboardWidget: typeof import('./src/components/Dashboard/DashboardWidget.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    EditExpense: typeof import('./src/components/Finances/Expenses/EditExpense.vue')['default']
    EditTask: typeof import('./src/components/Agenda/EditTask.vue')['default']
    EditTransaction: typeof import('./src/components/Finances/EditTransaction.vue')['default']
    ExpensesList: typeof import('./src/components/Finances/Expenses/ExpensesList.vue')['default']
    ExpensesWidget: typeof import('./src/components/Dashboard/ExpensesWidget.vue')['default']
    FitnessWidget: typeof import('./src/components/Dashboard/FitnessWidget.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputDialog: typeof import('./src/components/InputDialog.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
    Task: typeof import('./src/components/Agenda/Task.vue')['default']
    TasksWidget: typeof import('./src/components/Dashboard/TasksWidget.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TransactionHistory: typeof import('./src/components/Finances/TransactionHistory.vue')['default']
    WeatherHour: typeof import('./src/components/Dashboard/Weather/WeatherHour.vue')['default']
    WeatherWidget: typeof import('./src/components/Dashboard/Weather/WeatherWidget.vue')['default']
    WorkoutCalendar: typeof import('./src/components/Fitness/WorkoutCalendar.vue')['default']
    WorkoutCard: typeof import('./src/components/Fitness/WorkoutCard.vue')['default']
    WorkoutDot: typeof import('./src/components/Fitness/WorkoutDot.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
